Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'MCApplication/src')
src	= Glob('*.c')


CPPPATH = [cwd, str(Dir('#'))]


group = DefineGroup('MCApplication', src, depend = ['RT_USING_MCLIB'], CPPPATH = CPPPATH)



Return('group')
