Import('RTT_ROOT')
Import('rtconfig')
from building import *

SConscript(['interface/SConscript'])

SConscript(['inc/SConscript'])

SConscript(['src/SConscript'])

cwd     = os.path.join(str(Dir('#')), 'MCApplication')

src	= Glob('*.c')


CPPPATH = [cwd, str(Dir('#'))]
CPPDEFINES = ['STM32F40XX']

group = DefineGroup('MCApplication', src, depend = ['RT_USING_MCLIB'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)



Return('group')
