Import('RTT_ROOT')
Import('rtconfig')
from building import *

SConscript(['interface/SConscript'])

SConscript(['inc/SConscript'])

SConscript(['src/SConscript'])

cwd     = os.path.join(str(Dir('#')), 'MCLibrary')
src	= []
#src	= Glob('*.c')


CPPPATH = [cwd, str(Dir('#'))]


group = DefineGroup('MCLibrary', src, depend = ['RT_USING_MCLIB'], CPPPATH = CPPPATH)



Return('group')
