SET PATH=C:\Keil_v5\ARM\ARMCC\bin\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Python27\Scripts;C:\Python27;E:\MATLAB\R2014a\runtime\win64;E:\MATLAB\R2014a\bin;E:\MATLAB\R2014a\polyspace\bin;C:\Program Files (x86)\Altium Designer 6\System
SET CPU_TYPE=STM32F405RG
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=rt-thread_stm32f4xx
SET CPU_CLOCK=0x007A1200
"C:\Keil_v5\ARM\ARMCC\bin\ArmCC" --Via ".\build\application.__i"
"C:\Keil_v5\ARM\ARMCC\bin\ArmCC" --Via ".\build\startup.__i"
